import Head from "next/head";
import css from "../../styles/SignIn.module.css";
import { Layout } from "../../components";

export default function signin() {
  return (
    <Layout>
      <Head>
        <title>Sign In — Secure Checkout - Apple (Malaysia)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/apple-logo.png" />
      </Head>

      <div className={css.ContainerSection}>
        <div className={css.container}>
          <div className={css.signInHeader}>
            <h1>Sign in for faster checkout.</h1>
          </div>

          <div className={css.SignInForm}>
            <h2>Sign in to Apple Store</h2>
            <br />
          </div>

          <div className={css.formTable}>
            <form>
              <label>
                <input type="email" placeholder="Apple ID" />
              </label>
              <br />
              <label>
                <input type="password" placeholder="password" />
              </label>
              <br />
              <button>Sign In</button>
            </form>
          </div>
        </div>
      </div>
    </Layout>
  );
}
