import Head from "next/head";
import { Announcement, Product, FirstGrid, SecondGrid, ThirdGrid } from "../components";
import { client } from "../lib/client";

export default function Home({ products, firstGridData, secondGridData, thirdGridData }) {
  console.log(firstGridData, "HERE");
  return (
    <div>
      <Head>
        <title>Apple (Malaysia)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/apple-logo.png" />
      </Head>
      {/* body */}
      <main>
        <Announcement />
        {products.map((product) => (
          <Product key={product._id} product={product} />
        ))}

        <FirstGrid firstGridData={firstGridData} />

        <SecondGrid secondGridData={secondGridData} />

        <ThirdGrid thirdGridData={thirdGridData} />
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const firstGridQuery = '*[_type == "first_grid"]';
  const firstGridData = await client.fetch(firstGridQuery);

  const secondGridQuery = '*[_type == "second_grid"]';
  const secondGridData = await client.fetch(secondGridQuery);

  const thirdGridQuery = '*[_type == "third_grid"]';
  const thirdGridData = await client.fetch(thirdGridQuery);

  return {
    props: {
      products,
      firstGridData,
      secondGridData,
      thirdGridData
    },
  };
};
